// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEY1rG80uxybNSpN7w9O1T3S23BQJvHmk',
    appId: '1:440098686866:web:76845a618140cad78b634b',
    messagingSenderId: '440098686866',
    projectId: 'capstone-8e33e',
    authDomain: 'capstone-8e33e.firebaseapp.com',
    storageBucket: 'capstone-8e33e.firebasestorage.app',
    measurementId: 'G-VV0PZ6N32N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CprwrJWu-cTjQineP_H_yD0BlMFhUfE',
    appId: '1:440098686866:android:dfea3476582d0e128b634b',
    messagingSenderId: '440098686866',
    projectId: 'capstone-8e33e',
    storageBucket: 'capstone-8e33e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7DO2ZRioxTmFabB_zY9LlbUPn7YamMM',
    appId: '1:440098686866:ios:6b41e2a5aa25601b8b634b',
    messagingSenderId: '440098686866',
    projectId: 'capstone-8e33e',
    storageBucket: 'capstone-8e33e.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW7DO2ZRioxTmFabB_zY9LlbUPn7YamMM',
    appId: '1:440098686866:ios:6b41e2a5aa25601b8b634b',
    messagingSenderId: '440098686866',
    projectId: 'capstone-8e33e',
    storageBucket: 'capstone-8e33e.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEY1rG80uxybNSpN7w9O1T3S23BQJvHmk',
    appId: '1:440098686866:web:bb77676f1d0a6b668b634b',
    messagingSenderId: '440098686866',
    projectId: 'capstone-8e33e',
    authDomain: 'capstone-8e33e.firebaseapp.com',
    storageBucket: 'capstone-8e33e.firebasestorage.app',
    measurementId: 'G-R07PSB2WSN',
  );
}
